on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_USER: if0_38906542
          MYSQL_PASSWORD: wXILjNCSGD
          MYSQL_DATABASE: if0_38906542_abz
          MYSQL_ROOT_PASSWORD: root
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: |
          php --version
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
          chmod -R 777 storage bootstrap/cache
      - name: Generate key
        run: php artisan key:generate
      - name: Create Database Schema
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: if0_38906542_abz
#          DB_HOST: sql102.infinityfree.com
          DB_PORT: 33306
          DB_USERNAME: if0_38906542
          DB_PASSWORD: wXILjNCSGD
        run: php artisan migrate:fresh
#      - name: Optimize clear
#       run: php artisan optimize:clear
#      - name: Directory Permissions
#        run: chmod -R 777 storage bootstrap/cache

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftpupload.net
          server-dir: htdocs/
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}

